version: '3'
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
    command: postgresql:5432

  postgresql:
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always

  mlflow:
    build: .
    container_name: mlflow
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    depends_on:
      - postgresql
      - waitfordb
    volumes:
      - ${ARTIFACT_PATH}:${ARTIFACT_PATH}
    environment:
      DB_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/mlflow-db
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: ${MLFLOW_PORT}
      ARTIFACT_PATH: ${ARTIFACT_PATH}
    command: ./start.sh
    # <<debug>>
    # stdin_open: true
    # tty: true
    # command: /bin/bash
